export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_INIT = 'PURCHASE_INIT';

export const PURCHSE_BURGER_SUCCESS = 'PURCHSE_BURGER_SUCCESS';
export const PURCHSE_BURGER_FAIL = 'PURCHSE_BURGER_FAIL';
export const PURCHSE_BURGER_START = 'PURCHSE_BURGER_START';

export const FETCH_ORDERS_INIT = 'FETCH_ORDERS_INIT';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILED = 'FETCH_ORDERS_FAILED';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_TOAST_RESET = 'AUTH_TOAST_RESET';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';