export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
export const PURCHSE_BURGER_SUCCESS = 'PURCHSE_BURGER_SUCCESS';
export const PURCHSE_BURGER_FAIL = 'PURCHSE_BURGER_FAIL';
export const PURCHSE_BURGER_START = 'PURCHSE_BURGER_START';